# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()

[cijoe.transport.qemu_guest]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[cijoe.workflow]
fail_fast = true

# Used by: the qemu.*.py scripts
[qemu]
img_bin = "qemu-img"

# Used by: qemu.guest_initialize.py, qemu.guest_start.py, and qemu.guest_kill.py
[qemu.guests.generic-bios-kvm-x86_64]
path = "{{ local.env.HOME }}/guests/generic-bios-kvm-x86_64"
# Label of the qemu-system emulerator to use; see "qemu.systems"
system_label = "x86_64"
# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "host", smp = 8, m = "12G", accel = "kvm"}
# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "type=q35,kernel_irqchip=split" \
-device "intel-iommu,pt=on,intremap=on" \
"""
# TCP_FORWARD: Setup ssh forward from host to guest
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.tcp_forward = {host = 4200, guest = 22}

[qemu.systems.x86_64]
bin = "qemu-system-x86_64"

# SYSTEM_IMAGING: A collection of system images in the form of cloudimages,
# diskimages, and docker images.
#
[system-imaging.images.freebsd-14-x86_64]
system_label = "x86_64"
# cloud.decompressed_path = "{{ local.env.HOME }}/system_imaging/cloud/FreeBSD-14.2-RELEASE-amd64-BASIC-CLOUDINIT.zfs.qcow2"
# cloud.url ="https://download.freebsd.org/releases/VM-IMAGES/14.2-RELEASE/amd64/Latest/FreeBSD-14.2-RELEASE-amd64-BASIC-CLOUDINIT.zfs.qcow2.xz"
cloud.url = "https://object-storage.public.mtl1.vexxhost.net/swift/v1/1dbafeefbd4f4c80864414a441e72dd2/bsd-cloud-image.org/images/freebsd/14.2/2024-12-08/zfs/freebsd-14.2-zfs-2024-12-08.qcow2"
# cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/FreeBSD-14.2-RELEASE-amd64-BASIC-CLOUDINIT.zfs.qcow2.xz"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/freebsd-14.2-zfs-2024-12-08.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-freebsd-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-freebsd-userdata'] }}"
# disk.path = "{{ local.env.HOME }}/system_imaging/disk/freebsd_14_x86_64.qcow2"
disk.path = "/__w/spdk-ci/spdk-ci/freebsd_14_x86_64.qcow2"
docker.name = "spdk-ci"
docker.tag = "freebsd_14"
