---
name: 'Checkout from Gerrit'
description: 'Checkout SPDK, using provided patch set or master'

inputs:
  gerrit_ref:
    description: 'Reference to specific Gerrit patch set'
    required: false
    default: ''
  spdk_path:
    description: 'Path where SPDK will be cloned'
    required: false
    default: '$GITHUB_WORKSPACE/spdk'
  spdk_branch:
    description: 'Branch to clone'
    required: false
    default: 'master'

runs:
  using: 'composite'
  steps:
  - name: Checkout the spdk repo from GitHub
    uses: actions/checkout@v4.1.7
    with:
      repository: spdk/spdk
      ref: ${{ inputs.spdk_branch }}
      submodules: recursive
      fetch-tags: true
      path: ${{ inputs.spdk_path }}
  - name: Start summary
    run: |
      echo "### Change Information" >> $GITHUB_STEP_SUMMARY
    shell: bash
  - name: Fetch the specific change from Gerrit
    if: ${{ inputs.gerrit_ref != '' }}    # Skip if only pulling from GitHub
    working-directory: ${{ inputs.spdk_path }}
    run: |
      git fetch https://review.spdk.io/spdk/spdk ${{ inputs.gerrit_ref }} &&
      git checkout FETCH_HEAD &&
      git submodule update --init
      echo "- [SPDK Repository] Gerrit: ${{ inputs.gerrit_ref }}" >> $GITHUB_STEP_SUMMARY
    shell: bash
  - name: Add summary for GitHub repo
    if: ${{ inputs.gerrit_ref == '' }}
    run: |
      echo "- [SPDK Repository] GitHub: ${{ inputs.spdk_branch }}" >> $GITHUB_STEP_SUMMARY
    shell: bash
  - name: Unshallow SPDK repository
    working-directory: ${{ inputs.spdk_path }}
    run: |
      git fetch --unshallow --recurse-submodules=no
    shell: bash
  - name: Add Information on the SPDK repository state
    working-directory: ${{ inputs.spdk_path }}
    run: |
      CURRENT_REF=$(git log --pretty=oneline --abbrev-commit -n 1)
      echo "- Ref: $CURRENT_REF" >> $GITHUB_STEP_SUMMARY
    shell: bash
