---
name: SPDK per-patch tests

on:
  pull_request:
    paths-ignore:
    - '.github/workflows/selftest.yml'
    - '.github/workflows/build_qcow2.yml'
  workflow_dispatch:
  repository_dispatch:
    types:
    - per-patch-event

jobs:
  common:
    uses: ./.github/workflows/spdk-common-tests.yml
    with:
      # "Client payload" is all of the information Gerrit webhooks sends out.
      client_payload: ${{ toJson(github.event.client_payload) }}
  # Add more jobs below if needed.


  # Summary should be last job, please make sure to include yours in 'needs'.
  summary:
    if: ${{ always() }}
    needs: [common]
    uses: ./.github/workflows/summary.yml
    with:
      client_payload: ${{ toJson(github.event.client_payload) }}
    secrets: inherit
