---
name: False positive rerun

# Pull request - "SPDK-CI: PR#123: Example Title"
# Workflow dispatch - "Manual: (12345/5)Example Gerrit Subject"
# Repository dispatch - "(12345/5)Example Gerrit Subject"
run-name: >-
  ${{
    github.event_name == 'pull_request' && format('SPDK-CI: PR#{0}: {1}',
       github.event.pull_request.number, github.event.pull_request.title)
    || github.event_name == 'workflow_dispatch' && inputs.client_payload != '' && format('Manual: ({0}/{1}){2}',
       fromJson(inputs.client_payload).change.number, fromJson(inputs.client_payload).patchSet.number, fromJson(inputs.client_payload).change.subject)
    || github.event_name == 'workflow_dispatch' && inputs.client_payload == '' && format('Manual: SPDK master')
    || github.event_name == 'repository_dispatch' && github.event.client_payload != '' && format('({0}/{1}){2}',
       github.event.client_payload.change.number, github.event.client_payload.patchSet.number, github.event.client_payload.change.subject)
    || format('SPDK per-patch')
  }}

on:
  workflow_dispatch:
    inputs:
      client_payload:
        required: false
        type: string
        default: ''
  repository_dispatch:
    types:
    - comment-added

jobs:
  parse_comment:
    runs-on: ubuntu-latest
    if: github.event.client_payload || inputs.client_payload != ''
    env:
      client_payload: ${{ github.event.client_payload && toJson(github.event.client_payload) || inputs.client_payload }}
    steps:
    - uses: actions/checkout@v4
    - name: Parse for false positive
      run: .github/scripts/parse_false_positive_comment.sh
      env:
        GH_TOKEN: ${{ github.token }}
        change_num: ${{ fromJSON(env.client_payload).change.number }}
        patch_set: ${{ fromJSON(env.client_payload).patchSet.number }}
        COMMENT: ${{ fromJSON(env.client_payload).comment }}
        AUTHOR: ${{ fromJSON(env.client_payload).author.username }}
        REPO: ${{ github.repository_owner }}/spdk
        GH_REPO: ${{ github.repository }}
        GERRIT_BOT_USER: ${{ secrets.GERRIT_BOT_USER }}
        GERRIT_BOT_HTTP_PASSWD: ${{ secrets.GERRIT_BOT_HTTP_PASSWD }}
        GH_ISSUES_PAT: ${{ secrets.GH_ISSUES_PAT }}
