---
name: Gerrit outdated changes scan

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"    # Every 24 hours at midnight UTC

jobs:
  outdated-changes-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygerrit2

    - name: Run outdated changes script
      run: python .github/scripts/outdated_changes.py
      env:
        GERRIT_USERNAME: ${{ secrets.GERRIT_BOT_USER }}
        GERRIT_PASSWORD: ${{ secrets.GERRIT_BOT_HTTP_PASSWD }}
