---
name: SPDK per-patch tests

on:
  pull_request:
    paths-ignore:
    - '.github/workflows/selftest.yml'
    - '.github/workflows/build_qcow2.yml'
    - 'infra/**'
  workflow_dispatch:
    inputs:
      client_payload:
        required: false
        type: string
        default: ''
  repository_dispatch:
    types:
    - per-patch-event
    - patchset-created
    - wip-state-changed
    - private-state-changed

env:
  # TODO: Renable client_payload for workflow_dispatch
  client_payload: ${{ github.event.client_payload != '' && toJson(github.event.client_payload) || '' }}

jobs:
  env_vars: # Workaround for https://github.com/actions/runner/issues/2372
    runs-on: ubuntu-latest
    outputs:
      client_payload: ${{ env.client_payload }}
    steps:
    - run: echo "Passing workflow env vars to reusable workflows"

  patch_set_status:
    needs: env_vars
    runs-on: ubuntu-latest
    if: ${{ needs.env_vars.outputs.client_payload }}
    env:
      GH_TOKEN: ${{ github.token }}
      change_num: ${{ fromJSON(needs.env_vars.outputs.client_payload).change.number }}
      patch_set: ${{ fromJSON(needs.env_vars.outputs.client_payload).patchSet.number }}
    steps:
    - name: Check patch set status
      run: |
        set -e
        set -x

        # Get latest info about a change itself
        curl -s -X GET "https://review.spdk.io/a/changes/spdk%2Fspdk~${{ env.change_num }}?o=DETAILED_ACCOUNTS&o=LABELS&o=SKIP_DIFFSTAT" \
        --user "${{ secrets.GERRIT_BOT_USER }}:${{ secrets.GERRIT_BOT_HTTP_PASSWD }}" \
        | tail -n +2 > change.json

        # Do not test any change marked as WIP
        # .work_in_progress is not set when false
        work_in_progress="$(jq -r '.work_in_progress' change.json)"
        if [[ "$work_in_progress" == "true" ]]; then
          gh run cancel ${{ github.run_id }} -R ${{ github.repository }}
        fi

        # Only test latest patch set
        current_patch_set="$(jq -r '.current_revision_number' change.json)"
        if ((current_patch_set != ${{ env.patch_set }})); then
          gh run cancel ${{ github.run_id }} -R ${{ github.repository }}
        fi

        # Test only changes without a Verified vote already present
        verified=$(jq -r ".labels.Verified.all[]? | select(.username==\"${{ secrets.GERRIT_BOT_USER }}\").value" change.json)
        if ((verified != 0)); then
          gh run cancel ${{ github.run_id }} -R ${{ github.repository }}
        fi

  common:
    if: ${{ !cancelled() }}
    needs:
    - env_vars
    - patch_set_status
    uses: ./.github/workflows/spdk-common-tests.yml
    with:
      # "Client payload" is all of the information Gerrit webhooks sends out.
      client_payload: ${{ needs.env_vars.outputs.client_payload }}

  hpe:
    if: ${{ !cancelled() }}
    needs:
    - env_vars
    - patch_set_status
    uses: ./.github/workflows/nvmf-rdma.yml
    with:
      client_payload: ${{ needs.env_vars.outputs.client_payload }}
  # Add more jobs below if needed.


  # Summary should be last job, please make sure to include yours in 'needs'.
  summary:
    if: ${{ !cancelled() }}
    needs:
    - env_vars
    - patch_set_status
    - common
    - hpe
    uses: ./.github/workflows/summary.yml
    with:
      client_payload: ${{ needs.env_vars.outputs.client_payload }}
      result: ${{ needs.common.result }}
    secrets: inherit
