---
name: SPDK per-patch tests

on:
  pull_request:
    paths-ignore:
    - '.github/workflows/selftest.yml'
    - '.github/workflows/build_qcow2.yml'
  workflow_dispatch:
  repository_dispatch:
    types:
    - per-patch-event
    - patchset-created
    - wip-state-changed
    - private-state-changed

env:
  client_payload: ${{ github.event.client_payload || '' }}

jobs:
  env_vars: # Workaround for https://github.com/actions/runner/issues/2372
    runs-on: ubuntu-latest
    outputs:
      client_payload: ${{ env.client_payload }}
    steps:
    - run: echo "Passing workflow env vars to reusable workflows"

  common:
    needs: env_vars
    uses: ./.github/workflows/spdk-common-tests.yml
    with:
      # "Client payload" is all of the information Gerrit webhooks sends out.
      client_payload: ${{ needs.env_vars.outputs.client_payload }}

  hpe:
    needs: env_vars
    uses: ./.github/workflows/nvmf-rdma.yml
    with:
      client_payload: ${{ needs.env_vars.outputs.client_payload }}
  # Add more jobs below if needed.


  # Summary should be last job, please make sure to include yours in 'needs'.
  summary:
    if: ${{ !cancelled() }}
    needs:
    - env_vars
    - common
    - hpe
    uses: ./.github/workflows/summary.yml
    with:
      client_payload: ${{ needs.env_vars.outputs.client_payload }}
      result: ${{ needs.common.result }}
    secrets: inherit
