---
name: nvmf-rdma-test

on:
  workflow_call:
    inputs:
      client_payload:
        required: false
        type: string
        default: ''

jobs:
  hpe-nvmf-rdma:
    runs-on: [hpe-rdma-vm]
    env:
      gerrit_ref: ${{ inputs.client_payload != '' && fromJson(inputs.client_payload).patchSet.ref || inputs.gerrit_ref }}
      spdk_path: './spdk'
    steps:
      # Required to use locally defined actions
    - name: Checkout the spdk-ci repo locally
      uses: actions/checkout@v4
    - name: Checkout SPDK repo from Gerrit
      uses: ./.github/actions/checkout_gerrit
      with:
        gerrit_ref: ${{ env.gerrit_ref }}
        spdk_path: ${{ env.spdk_path }}
    - name: autorun-nvmf
      run: |
        cat > funtest.conf << EOF
        SPDK_RUN_FUNCTIONAL_TEST=1
        SPDK_TEST_NVMF=1
        SPDK_TEST_NVMF_TRANSPORT="rdma"
        SPDK_TEST_NVMF_NICS=mlx5
        NET_TYPE=phy
        SPDK_RUN_ASAN=0
        SPDK_RUN_UBSAN=1
        EOF
        ./spdk/autorun.sh ./funtest.conf
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.4.0
      if: always()
      with:
        path: ./output
        name: nvmf-rdma-vm_artifacts
