---
name: per_patch

on:
  workflow_call:

jobs:
  autorun:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    env:
      REPOSITORY_TARBALL_PATH: ${{ github.workspace }}/repository.tar.gz
      CI_CFGS_REPOSITORY_PATH: ${{ github.workspace }}/ci/cijoe/configs/autorun_configs
    strategy:
      matrix:
        workflow: [autorun_unittest, autorun_nvme]
    container:
      image: ghcr.io/refenv/cijoe-docker:v0.9.50
      options: --device=/dev/kvm

    steps:
    - name: Setup PATH
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Checkout CI repository
      uses: actions/checkout@v4.1.7
      with:
        path: ci

    - name: Download the SPDK repository
      uses: actions/download-artifact@v4.1.8
      with:
        name: repository

    - name: Extract the SPDK repository
      run: |
        tar xzf repository.tar.gz --strip 1

    - name: Download VM Qcow2 image artifact
      uses: actions/download-artifact@v4.1.8
      # TODO: run_id is hardocded, for now.
      # In future it'd be best to dynamically fetch latest successful build.
      with:
        name: qcow2-build-artifacts
        github-token: ${{ github.token }}
        run-id: 13388420961

    - name: qemu-guest, provision
      run: |
        cd ci/cijoe
        cijoe guest_initialize guest_start guest_check tgz_transfer ci_configs_transfer tgz_unpack \
        --monitor \
        --config configs/qemuhost-with-guest-fedora-40.toml \
        --workflow workflows/autorun_in_qemu.yaml \
        --output report_${{ matrix.workflow }}_prep_guest

    - name: qemu-guest, ${{ matrix.workflow }}
      run: |
        cd ci/cijoe
        cijoe ${{ matrix.workflow }} \
        --monitor \
        --config configs/qemuhost-with-guest-fedora-40.toml \
        --workflow workflows/autorun_in_qemu.yaml \
        --output report_${{ matrix.workflow }}

    - name: qemu-guest, cleanup
      if: always()
      run: |
        cd ci/cijoe
        cijoe output_listing retrieve_autorun_output guest_shutdown \
        --monitor \
        --config configs/qemuhost-with-guest-fedora-40.toml \
        --workflow workflows/autorun_in_qemu.yaml \
        --output report_${{ matrix.workflow }}_cleanup

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.4.0
      if: always()
      with:
        path: /tmp/autorun_output
        name: ${{ matrix.workflow }}_artifacts

    - name: Upload Report
      uses: actions/upload-artifact@v4.4.0
      if: always()
      with:
        path: |
          ci/cijoe/report_${{ matrix.workflow }}
          ci/cijoe/report_${{ matrix.workflow }}_cleanup
          ci/cijoe/report_${{ matrix.workflow }}_prep_guest
        name: report-${{ matrix.workflow }}-in-qemu
